version: '2'
services:
  db:
    image: mysql:5.6
    restart: always
    env_file:
      - ./.docker.env
    ports:
      - "3307:3306"
    volumes:
      - "./.mysql-data:/var/lib/mysql"

  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    hostname: dockerlocal
    env_file:
      - ./.docker.env
    ports:
      - "8080:80"
    volumes:
      - ./../web:/var/www/site
      - ./config/httpd.conf:/etc/apache2/httpd.conf
      - ./config/vhost.conf:/etc/apache2/vhost.conf
      - ./config/php.ini:/etc/php5/php.ini
    links:
      - db
    environment:
      MYSQL_HOST: db